services:
  backend:
    build:
      context: "."
      dockerfile: "./docker/backend.dockerfile"
    env_file: server/.env
    ports:
      - "10000:10000"

  frontend:
    build:
      context: "."
      dockerfile: "./docker/frontend.dockerfile"
      args:
        APP_PATH: /
    environment:
      API_BASE_URL: http://backend:10000
      APP_PATH: /
    ports:
      - "3000:80"

  worker:
    profiles:
      - worker
    build:
      context: "."
      dockerfile: "./docker/cpu-worker.dockerfile"
    volumes:
      - ./data:/data
    env_file: worker/.env

  batch-worker:
    profiles:
      - batch-worker
    build:
      context: "."
      dockerfile: "./docker/batch-gpu-worker.dockerfile"
    volumes:
      - ./data:/data
    env_file: worker/.env
    # entrypoint: "node app.js"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
