services:
  backend:
    build:
      context: "."
      dockerfile: "./docker/backend.dockerfile"
    volumes:
      - ./data:/app/data
    env_file: server/.env
    ports:
      - "9000:9000"
    volumes:
      - ./data:/data

  # frontend:
  #   build:
  #     context: "."
  #     dockerfile: "./docker/frontend.dockerfile"
  #     args:
  #       NEXT_PUBLIC_API_BASE_URL: http://backend:9000
  #   ports:
  #     - "3000:80"

  worker:
    profiles:
      - worker
    build:
      context: "."
      dockerfile: "./docker/cpu-worker.dockerfile"
    volumes:
      - ./data:/data
    env_file: server/.env
    entrypoint: "node app.js 1" 

  batch-worker:
    profiles:
      - batch-worker
    build:
      context: "."
      dockerfile: "./docker/batch-gpu-worker.dockerfile"
    volumes:
      - ./data:/data
    env_file: worker/.env
    # entrypoint: "node app.js"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
